version: '2.1'

# Services
services:
  todo:
    build: kata-1
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  mysql:
    image: mysql:5.7
    mem_limit: 350m
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=todo-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uuser", "-ppwd", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - todo-data:/var/lib/mysql
      
# Volumes
volumes:
  todo-data: