server.port: 8081

logging:
  level:
    root: INFO
    me.arthur: DEBUG

spring.jpa.hibernate.ddl-auto: update

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/todo
    username: user
    password: pwd

spring.datasource.hikari.initializationFailTimeout: 60000

---
spring.config.activate.on-profile: docker

server.port: 8080
spring.datasource:
  url: jdbc:mysql://todo-db/todo-db