# import application-oauth.yml
spring.profiles.include: oauth

server.port: 8080

logging:
  level:
    root: INFO
    me.arthur: DEBUG

# spring.jpa.hibernate.ddl-auto: update
# spring.datasource.hikari.initializationFailTimeout: 60000

# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3308/user-db
#     username: user
#     password: pwd

# app:
#   todo-service:
#     host: localhost
#     port: 8090

should-do:
  host: localhost
  port: 8090
---
spring.config.activate.on-profile: docker

server.port: 8080
# spring.datasource:
#   url: jdbc:mysql://user-db/user-db

# app:
#   todo-service:
#     host: todo-service
#     port: 8080

should-do:
  host: todo-service
  port: 8080