# import application-oauth.yml
spring.profiles.include: oauth

server.port: 8080

logging:
  level:
    root: INFO
    me.arthur: DEBUG

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      # - myandroidapp://oauth2/redirect
      # - myiosapp://oauth2/redirect

spring.jpa.hibernate.ddl-auto: update
spring.datasource.hikari.initializationFailTimeout: 60000

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/user-db
    username: user
    password: pwd

---
spring.config.activate.on-profile: docker

server.port: 8080
spring.datasource:
  url: jdbc:mysql://user-db/user-db