server.port: 8080

logging:
  level:
    root: INFO
    me.arthur: DEBUG

spring.jpa.hibernate.ddl-auto: update

spring:
  datasource:
    url: jdbc:mysql://localhost/todo-db
    username: user
    password: pwd

spring.datasource.hikari.initializationFailTimeout: 60000

---
spring.config.activate.on-profile: docker

spring.datasource:
  url: jdbc:mysql://mysql-db/todo-db

server.port: 8080
